#!/usr/bin/env python3
"""Genera videos.json — pool di sample CAMPIONABILI per UMDB Sample Roulette.

Architettura ibrida (v2):
  1) DISCOVERY gratis con yt-dlp (nessuna quota YouTube) su tutte le query, ogni notte
  2) VALIDAZIONE economica via YouTube Data API videos.list (1 unita'/50 id)
Cosi' il costo API e' ~(#candidati+#esistenti)/50 unita' (~decine), niente piu' 429.

Filtri (digger underground, roba da choppare):
  - categoria musica implicita nelle query, durata 45-600s
  - embeddable (cue istantaneo lato server)
  - views nell'intervallo [VIEW_MIN, VIEW_MAX]  (floor anti AI-slop, cap anti-famosi)
  - regex BAD: fuori type-beat/free/mix/live/karaoke + AI-slop/Indo-EDM/library/cover/remix
  - cap PER-CANALE: max PER_CHANNEL tracce dallo stesso uploader (diversita')
Rivalida sempre anche l'esistente: chi supera il cap, scende sotto il floor, diventa
famoso/rotto o matcha la nuova BAD viene rimosso in automatico.

Uso: build_pool_api.py [OUT_PATH]   (OUT_PATH opzionale per dry-run senza toccare il pool vero)
"""
import json, re, os, sys, subprocess
from collections import Counter
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "..", "videos.json")
TOKEN = "/home/francesco/miliardo-beats/01_ANALYTICS/api_privati/token.json"
YTDLP = "/home/francesco/.local/bin/yt-dlp"

VIEW_MIN    = 15      # sotto = quasi sempre AI-slop/spam appena caricato
VIEW_MAX    = 30000   # sopra = troppo noto, non e' piu' digging
DUR_MIN     = 45
DUR_MAX     = 600
PER_CHANNEL = 10      # max tracce dallo stesso canale (diversita' fonte)
SEARCH_N    = 40      # risultati per query via yt-dlp (profondo: i primi sono i popolari che il cap 30k scarta)

# Query mirate a materiale campionabile: strumentale/groove/vinile, con drum-break e
# generi che un digger Dilla/Madlib/Alchemist cerca. Niente 'breakbeat' generico
# (porta solo EDM indonesiano). Nomi di compositori library/giallo = originali, non imitazioni AI.
QUERIES = [
 # funk / soul core
 "funk instrumental","soul instrumental","rare groove funk","boogie funk","disco instrumental",
 "sweet soul","northern soul","psychedelic soul","gospel funk","rhythm and blues instrumental",
 "vintage soul 45","funk 45","soul 45","70s funk","60s soul","deep funk instrumental",
 "moog funk","rhodes soul instrumental","hammond organ funk","clavinet funk",
 # drum break isolati (il buco piu' grosso del pool)
 "funk drum break","open drums funk","drum break 45","soul drum break","isolated drums funk",
 "drum solo funk","organ drum break","live drum break funk",
 # jazz da campionare
 "jazz funk","jazz fusion instrumental","spiritual jazz","soul jazz organ","latin jazz",
 "jazz drums break","modal jazz","hard bop","library jazz",
 # library / soundtrack / giallo
 "library music","italian library music","french library music","kpm library",
 "cinematic soundtrack instrumental","giallo soundtrack","spy jazz","blaxploitation soundtrack",
 "lounge exotica","Piero Umiliani","Alessandro Alessandroni","Piero Piccioni","Stelvio Cipriani",
 "Janko Nilovic","Bruton music","De Wolfe music",
 # groove globale (dove vivono le gemme oscure)
 "afrobeat instrumental","highlife","ethio jazz","zamrock","nigerian funk","ghana funk",
 "turkish funk","turkish psych","brazilian funk","samba rock","bossa nova instrumental",
 "tropicalia","brazilian groove","peruvian cumbia","cumbia funk","salsa dura","boogaloo",
 "japanese city pop","japanese funk","korean funk","thai funk","cambodian rock",
 "bollywood funk","indian funk","spanish funk","krautrock instrumental","dub instrumental",
 "reggae instrumental","garage rock instrumental","psych rock instrumental",
]

# --- filtro qualita' sui titoli -------------------------------------------------
# Ancorati (\b, forme-tag) per non uccidere gemme: 'free' solo tra parentesi (salva 'free jazz'),
# 'live at/in' con boundary (salva 'Alive Inside'), 'best of' solo in forma-compilation.
# 'mix'/'remix' NON qui: gestiti a parte con guardia vintage (vedi MIXY/VINTAGE) per salvare i 12"/extended/dub.
# L'anno 20xx nel titolo = re-upload/AI/finto-vintage.
BAD = re.compile(
    r'(\btype beat\b|typebeat|[\[({]\s*free\s*[\]})]|free download|free dl|prod\.|prod by|no copyright|copyright free|'
    r'audio library|royalty[ -]?free|background music|'
    r'\b1 hour\b|\b2 hour\b|\b3 hour\b|full album|nonstop|non-stop|megamix|mega mix|dj mix|continuous|'
    r'karaoke|tutorial|how to|reaction|\blive (at|in)\b|lyrics?|documentary|interview|'
    r'top \d|greatest hits|best of the \d0s|best of vol|compilation|playlist|mixtape|dj set|full ep|full lp|'
    r'sped up|speed ?up|slowed|remaster|nightcore|phonk|\bcover\b|'
    r'full ?bass|full baas|terbaru|dangdut|mangkane|montagem|\bfyp\b|tiktok|'
    r'\bsuno\b|ai generated|ai music|ai cover|generated by ai|8[ -]?bit|\bmidi\b|'
    r'neurofunk|drum\s*(&|and|n)\s*bass|\bdnb\b|snippet|#short|backing track|play ?along|jam track|'
    r'\bbaqueta\b|\baula\b|como (tocar|segurar|fazer)|\blesson\b|how to (play|hold)|'
    r'\b20(1\d|2\d)\b)', re.I)
# mix/remix: butta solo se il titolo NON sembra vintage/campionabile. Salva 12"/extended/dub/instrumental
# e i dischi anni '50-'90 (italo-disco '82, ecc.), uccide il remix/mix moderno senza marca d'epoca.
MIXY    = re.compile(r'\bmix\b|remix', re.I)
VINTAGE = re.compile(r'19[5-9]\d|12["”″\']|extended|\bdub\b|instrumental|\bversion\b|\bedit\b', re.I)

def iso_to_sec(s):
    m = re.match(r'PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?', s or '')
    if not m: return 0
    h, mi, se = (int(x) if x else 0 for x in m.groups())
    return h*3600 + mi*60 + se

def ytdlp_ids(q, n=SEARCH_N):
    try:
        out = subprocess.run(
            [YTDLP, "--flat-playlist", "--no-warnings", "--print", "%(id)s", f"ytsearch{n}:{q}"],
            capture_output=True, text=True, timeout=90).stdout
        return [l.strip() for l in out.splitlines() if len(l.strip()) == 11]
    except Exception as e:
        print(f"  ytdlp err '{q}': {str(e)[:60]}")
        return []

def ytdlp_channel(ch, n=40):
    """Uploads di un canale (channel-mining delle vene proven). Costo quota API: 0."""
    try:
        out = subprocess.run(
            [YTDLP, "--flat-playlist", "--no-warnings", "--playlist-end", str(n),
             "--print", "%(id)s", f"https://www.youtube.com/channel/{ch}/videos"],
            capture_output=True, text=True, timeout=120).stdout
        return [l.strip() for l in out.splitlines() if len(l.strip()) == 11]
    except Exception as e:
        print(f"  chan err {ch}: {str(e)[:50]}")
        return []

# Modificatori a rotazione: ogni notte le query base vengono variate con decennio/label,
# aprendo sotto-spazi diversi (probe misurato: ~77 nuovi/notte, 92% nuovi). _doy = giorno dell'anno.
import datetime
_doy = datetime.date.today().timetuple().tm_yday
BASE_MOD = ["brazilian funk","spiritual jazz","turkish funk","soul instrumental","jazz funk",
            "afrobeat","library music","italian library music","boogaloo","ethio jazz",
            "japanese funk","peruvian cumbia","northern soul","deep funk"]
DECADI = ["1969","1971","1972","1974","1976","1978","1981"]
LABEL  = ["KPM","CTI","Kudu","Blue Note","Bruton","De Wolfe","Impulse","Prestige"]
EXTRA_QUERIES = []
for i, b in enumerate(BASE_MOD):
    EXTRA_QUERIES.append(f"{b} {DECADI[(_doy+i) % len(DECADI)]}")
    EXTRA_QUERIES.append(f"{b} {LABEL[(_doy+i) % len(LABEL)]}")

# 1) DISCOVERY per ricerca: query base + modificatori a rotazione (gratis) --------
cand = set()
QALL = QUERIES + EXTRA_QUERIES
for i, q in enumerate(QALL):
    got = ytdlp_ids(q)
    cand.update(got)
    print(f"  [{i+1}/{len(QALL)}] {q:34} +{len(got):2}  cand={len(cand)}")

# 2) esistente: titoli (fallback) + conteggio canali (per il mining) --------------
existing = {}
chan_count = Counter()
if os.path.exists(OUT):
    try:
        for v in json.load(open(OUT)):
            if v.get('id'):
                existing[v['id']] = v.get('t', '')
                if v.get('c'): chan_count[v['c']] += 1
    except Exception:
        pass

# 2b) CHANNEL-MINING: mina le vene proven (canali con 2..cap-1 tracce nel pool), a rotazione
#     notturna sui 188 canali (probe misurato: ~134 nuovi/notte, 100% nuovi, gemme). Quota API: 0.
proven = sorted(c for c, n in chan_count.items() if c and 2 <= n < PER_CHANNEL)
MINE_PER_NIGHT = 40
tonight = []
if proven:
    start = (_doy * MINE_PER_NIGHT) % len(proven)
    tonight = (proven[start:] + proven[:start])[:MINE_PER_NIGHT]
    for ci, ch in enumerate(tonight):
        got = ytdlp_channel(ch)
        cand.update(got)
        print(f"  [canale {ci+1}/{len(tonight)}] {ch} +{len(got):2}  cand={len(cand)}")

allids = list(cand | set(existing))
nuovi = len(cand - set(existing))
print(f"\nDa validare: {len(allids)}  (nuovi {nuovi} + esistenti {len(existing)}) | canali minati: {len(tonight)}")

# 3) VALIDAZIONE via API (batch da 50, 1 unita'/chiamata) -------------------------
creds = Credentials.from_authorized_user_file(TOKEN)
yt = build('youtube', 'v3', credentials=creds)
cands = {}
calls = 0
for i in range(0, len(allids), 50):
    batch = allids[i:i+50]
    try:
        vr = yt.videos().list(part='contentDetails,status,statistics,snippet',
                              id=','.join(batch)).execute()
        calls += 1
    except Exception as e:
        print(f"  videos.list err: {str(e)[:70]}")
        continue
    for it in vr.get('items', []):
        try:  # per-item: un video malformato non abortisce il batch da 50
            vid = it['id']
            d = iso_to_sec((it.get('contentDetails') or {}).get('duration'))
            st = it.get('status') or {}
            sn = it.get('snippet') or {}
            views = int((it.get('statistics') or {}).get('viewCount') or 10**9)  # senza view = sospetto -> fuori
            if d < DUR_MIN or d > DUR_MAX: continue
            if not st.get('embeddable', True): continue
            if views < VIEW_MIN or views > VIEW_MAX: continue
            full = sn.get('title') or existing.get(vid, '')
            if BAD.search(full): continue                       # regex sul titolo PIENO (marcatori in coda inclusi)
            if MIXY.search(full) and not VINTAGE.search(full): continue   # mix/remix moderno fuori, vintage dentro
            t = full[:80]                                        # tronco solo per lo storage
            cands[vid] = {"id": vid, "d": d, "t": t, "v": views, "c": sn.get('channelId') or ''}
        except Exception:
            continue
print(f"  validati (pre cap-canale): {len(cands)}  | {calls} chiamate API")

# 4) CAP PER-CANALE: tieni al max PER_CHANNEL per canale, preferendo i piu' oscuri --
final = []
seen_ch = Counter()
for v in sorted(cands.values(), key=lambda x: x['v']):   # views crescenti = piu' underground prima
    ch = v['c'] or v['id']
    if seen_ch[ch] >= PER_CHANNEL:
        continue
    seen_ch[ch] += 1
    final.append(v)

# 5) GUARDIA anti-wipe: MAI sovrascrivere il pool con un risultato degenere
#    (auth/quota/rete falliti in blocco -> cands vuoto). Uscendo non-zero, videos.json resta
#    intatto e refresh_pool.sh non committa/pusha (git diff --quiet resta vero).
prev = len(existing)
if calls == 0:
    sys.exit("⛔ ABORT: nessun batch API riuscito (auth/quota/rete) — pool NON toccato")
if not final or (prev and (len(final) < 500 or len(final) < 0.7 * prev)):
    sys.exit(f"⛔ ABORT: risultato sospetto ({len(final)} vs esistente {prev}) — pool NON toccato")

# 6) SCRITTURA ATOMICA + backup: mai lasciare videos.json vuoto o troncato (crash/OOM su hw debole)
tmp = OUT + ".tmp"
with open(tmp, "w", encoding="utf-8") as f:
    json.dump(final, f, ensure_ascii=False)
if os.path.exists(OUT):
    try:
        import shutil; shutil.copy2(OUT, OUT + ".prev")   # backup del pool precedente
    except Exception:
        pass
os.replace(tmp, OUT)                                       # rename atomico (stesso filesystem)
print(f"\n✅ POOL: {len(final)} sample campionabili | {len(seen_ch)} canali distinti | {calls} chiamate API")
print(f"   -> {os.path.abspath(OUT)}")
